# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [3]:
np.random.seed(2)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(4, 4, 3)
W = np.random.randn(4, 4, 3)
b = np.random.randn(1, 1, 1)

#取得計算後,卷績矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)


Z = -6.103434403368636


In [4]:
print(f'a_slice_prev:\n{a_slice_prev},\n----------------------------------\n W:\n{W},\n----------------------------------\n b:\n{b},\n----------------------------------\n Z:\n{Z}')

a_slice_prev:
[[[-4.16757847e-01 -5.62668272e-02 -2.13619610e+00]
  [ 1.64027081e+00 -1.79343559e+00 -8.41747366e-01]
  [ 5.02881417e-01 -1.24528809e+00 -1.05795222e+00]
  [-9.09007615e-01  5.51454045e-01  2.29220801e+00]]

 [[ 4.15393930e-02 -1.11792545e+00  5.39058321e-01]
  [-5.96159700e-01 -1.91304965e-02  1.17500122e+00]
  [-7.47870949e-01  9.02525097e-03 -8.78107893e-01]
  [-1.56434170e-01  2.56570452e-01 -9.88779049e-01]]

 [[-3.38821966e-01 -2.36184031e-01 -6.37655012e-01]
  [-1.18761229e+00 -1.42121723e+00 -1.53495196e-01]
  [-2.69056960e-01  2.23136679e+00 -2.43476758e+00]
  [ 1.12726505e-01  3.70444537e-01  1.35963386e+00]]

 [[ 5.01857207e-01 -8.44213704e-01  9.76147160e-06]
  [ 5.42352572e-01 -3.13508197e-01  7.71011738e-01]
  [-1.86809065e+00  1.73118467e+00  1.46767801e+00]
  [-3.35677339e-01  6.11340780e-01  4.79705919e-02]]],
----------------------------------
 W:
[[[-0.82913529  0.08771022  1.00036589]
  [-0.38109252 -0.37566942 -0.07447076]
  [ 0.43349633  1.27837923